api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('constructions/', views.getConstructions),
    path('constructions/<str:pk>/', views.getConstruction),
    path('constructions/<str:pk>/addearth/', views.addEarth),
    path('constructions/<str:pk>/addconcrete/', views.addConcrete),
    path('constructions/<str:pk>/addreinforcement/', views.addReinforcement),
    path('constructions/<str:pk>/addothers/', views.addOthers),

    path('remove-tag/', views.removeTag),
]

constructions/urls.py
from django.urls import path
from . import views

app_name = 'constructions'

urlpatterns = [
    path('', views.constructions, name='constructions'),
    path('construction/<str:pk>', views.construction, name='construction'),
    path('create-construction/', views.createConstruction, name='create-construction'),
    path('update-construction/<str:pk>', views.updateConstruction, name='update-construction'),
    path('delete-construction/<str:pk>', views.deleteConstruction, name='delete-construction'),

    path('earth-positions/<str:pk>', views.earthPositions, name='earth-positions'),
    path('concrete-positions/<str:pk>', views.concretePositions, name='concrete-positions'),
    path('reinforcement-positions/<str:pk>', views.reinforcementPositions, name='reinforcement-positions'),
    path('others-positions/<str:pk>', views.othersPositions, name='others-positions'),
    path('summary-positions/<str:pk>', views.summaryPositions, name='summary-positions'),

    path('add-earth-quantity/<str:pk>', views.addEarthQuantity, name='add-earth-quantity'),
    path('update-earth-quantity/<str:pk>', views.updateEarthQuantity, name='update-earth-quantity'),
    path('delete-earth-quantity/<str:pk>', views.deleteEarthQuantity, name='delete-earth-quantity'),

    path('add-concrete-quantity/<str:pk>', views.addConcreteQuantity, name='add-concrete-quantity'),
    path('update-concrete-quantity/<str:pk>', views.updateConcreteQuantity, name='update-concrete-quantity'),
    path('delete-concrete-quantity/<str:pk>', views.deleteConcreteQuantity, name='delete-concrete-quantity'),

    path('add-reinforcement-quantity/<str:pk>', views.addReinforcementQuantity, name='add-reinforcement-quantity'),
    path('update-reinforcement-quantity/<str:pk>', views.updateReinforcementQuantity, name='update-reinforcement-quantity'),
    path('delete-reinforcement-quantity/<str:pk>', views.deleteReinforcementQuantity, name='delete-reinforcement-quantity'),

    path('add-others-quantity/<str:pk>', views.addOthersQuantity, name='add-others-quantity'),
    path('update-others-quantity/<str:pk>', views.updateOthersQuantity, name='update-others-quantity'),
    path('delete-others-quantity/<str:pk>', views.deleteOthersQuantity, name='delete-others-quantity'),

    path('add-measure-unit/', views.addMeasureUnit, name='add-measure-unit'),
    path('remove-measure-unit/', views.removeMeasureUnit, name='remove-measure-unit'),

    path('export-excel/<str:pk>', views.exportExcel, name='export-excel'),
]

quantitycheck/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [   

    path('admin/', admin.site.urls),
    path('', include('constructions.urls')),    
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='reset_password_sent.html'), name='password_reset_done'),   
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='reset.html'), name='password_reset_confirm'),   
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'), name='password_reset_complete'),   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),

    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userProfile, name='user-profile'),

    path('account/', views.userAccount, name='account'),
    path('edit-account/', views.editAccount, name='edit-account'),
    path('delete-account/<str:pk>', views.deleteAccount, name='delete-account'),

    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.viewMessage, name='message'),
    path('create-message/<str:pk>/', views.createMessage, name='create-message'),
    path('delete-message/<str:pk>/', views.deleteMessage, name='delete-message'),
]

constructions/views.py
from django.shortcuts import render, redirect
from . models import Construction, Tag, Earth, Concrete, Reinforcement, Others, MeasureUnit
from . forms import ConstructionForm, EarthForm, ConcreteForm, ReinforcementForm, OthersForm, AddMeasureUnitForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . utils import searchConstructions, searchEarth, searchConcrete, searchReinforcement, searchOthers, paginateConstructions
from django.db.models import Sum, Q, Max
from django.http import HttpResponse
from datetime import datetime
import xlwt



# Constructions
def constructions(request):
    constructions, search_query = searchConstructions(request)   
    custom_range, constructions = paginateConstructions(request, constructions, 6)

    context = {'constructions': constructions, 'search_query': search_query, 'custom_range': custom_range}

    return render(request, 'constructions/constructions.html', context)

def construction(request, pk):
    constructionObj = Construction.objects.get(id=pk)
   
    context = {
        'construction':constructionObj,
    }
    
    return render(request, 'constructions/single-construction.html', context)

@login_required(login_url='users:login')
def createConstruction(request):
    profile = request.user.profile
    form = ConstructionForm()

    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',', ' ').split()

        form = ConstructionForm(request.POST, request.FILES)
        if form.is_valid():
            construction = form.save(commit=False)
            construction.owner = profile
            construction.save()

            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                construction.tags.add(tag)
                
            messages.success(request, 'Construction was added')
            return redirect('constructions:constructions')

    context = {
        'form':form,
    }
    return render(request, 'constructions/construction_form.html', context)

@login_required(login_url='users:login')
def updateConstruction(request, pk):
    profile = request.user.profile
    construction = profile.construction_set.get(id=pk)
    form = ConstructionForm(instance=construction)

    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',', ' ').split()
       
        form = ConstructionForm(request.POST, request.FILES, instance=construction)
        if form.is_valid():
            construction = form.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                construction.tags.add(tag)

            messages.success(request, 'Construction was updated')
            return redirect('users:account')

    context = {
        'form':form,
        'construction':construction,
    }
    return render(request, 'constructions/construction_form.html', context)

@login_required(login_url='users:login')
def deleteConstruction(request, pk):
    profile = request.user.profile
    construction = profile.construction_set.get(id=pk)
    if request.method == 'POST':
        construction.delete()
        messages.success(request, 'Construction was deleted')
        return redirect('constructions:constructions')
    context = {
        'object':construction,
    }
    return render(request, 'constructions/delete_template.html', context)

# Positions
def earthPositions(request, pk):
    constructionObj = Construction.objects.get(id=pk)
    quantities = searchEarth(request)

    context = {'construction':constructionObj, 'quantities':quantities}
    return render(request, 'constructions/earth_positions.html', context)

def concretePositions(request, pk):
    constructionObj = Construction.objects.get(id=pk)
    quantities = searchConcrete(request)

    context = {'construction':constructionObj, 'quantities':quantities}
    return render(request, 'constructions/concrete_positions.html', context)

def reinforcementPositions(request, pk):
    constructionObj = Construction.objects.get(id=pk)
    quantities = searchReinforcement(request)

    context = {'construction':constructionObj, 'quantities':quantities}
    return render(request, 'constructions/reinforcement_positions.html', context)

def othersPositions(request, pk):
    constructionObj = Construction.objects.get(id=pk)
    quantities = searchOthers(request)

    context = {'construction':constructionObj, 'quantities':quantities}
    return render(request, 'constructions/others_positions.html', context)

def summaryPositions(request, pk):
    constructionObj = Construction.objects.get(id=pk)

    earthSummary = Earth.objects.filter(Q(owner=constructionObj)).values('custom_name', 'measure_unit_dropdown__name').annotate(quantity=Sum('quantity')).order_by('custom_name')
    concreteSummary = Concrete.objects.filter(Q(owner=constructionObj)).values('custom_name', 'measure_unit_dropdown__name').annotate(quantity=Sum('quantity')).order_by('custom_name')
    reinforcementSummary = Reinforcement.objects.filter(Q(owner=constructionObj)).values('custom_name', 'measure_unit_dropdown__name').annotate(quantity=Sum('quantity')).order_by('custom_name')
    othersSummary = Others.objects.filter(Q(owner=constructionObj)).values('custom_name', 'measure_unit_dropdown__name').annotate(quantity=Sum('quantity')).order_by('custom_name')

    context = {'construction':constructionObj,
    'earthSummary':earthSummary,
    'concreteSummary':concreteSummary, 
    'reinforcementSummary':reinforcementSummary,
    'othersSummary':othersSummary,
    }

    return render(request, 'constructions/summary_positions.html', context)

# Earth operations
@login_required(login_url='users:login')
def addEarthQuantity(request, pk):
    constructionObj = Construction.objects.get(id=pk)    
    form = EarthForm()
       
    if request.method == 'POST':
        form = EarthForm(request.POST)
        if form.is_valid():
            quantity = form.save(commit=False)
            quantity.owner = constructionObj
            quantity.save()

            messages.success(request, 'Quantity was added')
            pre_url = '/earth-positions/{id}'.format(id=pk)
            return redirect(pre_url)

    context = {'form':form, 'construction':constructionObj}
    return render(request, 'constructions/add_quantity.html', context)

@login_required(login_url='users:login')
def updateEarthQuantity(request, pk):
    quantity = Earth.objects.get(id=pk)    
    constructionObj = quantity.owner

    form = EarthForm(instance=quantity)

    if request.method == 'POST':
        form = EarthForm(request.POST, instance=quantity)
        if form.is_valid():
            quantity = form.save(commit=False)
            quantity.save()
            messages.success(request, 'Quantity was updated')            
            pre_url = '/earth-positions/{id}'.format(id=quantity.owner.id)
            return redirect(pre_url)

    context = {'form':form, 'construction':constructionObj}
    return render(request, 'constructions/add_quantity.html', context)

@login_required(login_url='users:login')

def deleteEarthQuantity(request, pk):
    quantity = Earth.objects.get(id=pk)

    if request.method == 'POST':
        quantity.delete()
        messages.success(request, 'Quantity was deleted')
        pre_url = '/earth-positions/{id}'.format(id=quantity.owner.id)
        return redirect(pre_url)

    context = {
        'object':quantity,
    }
    
    return render(request, 'constructions/delete_template.html', context)

# Concrete operations
@login_required(login_url='users:login')
def addConcreteQuantity(request, pk):
    constructionObj = Construction.objects.get(id=pk)
    form = ConcreteForm()

    if request.method == 'POST':
        form = ConcreteForm(request.POST)
        if form.is_valid():
            quantity = form.save(commit=False)
            quantity.owner = constructionObj
            quantity.save()
            messages.success(request, 'Quantity was added')
            pre_url = '/concrete-positions/{id}'.format(id=pk)
            return redirect(pre_url)

    context = {'form':form, 'construction':constructionObj}
    return render(request, 'constructions/add_quantity.html', context)

@login_required(login_url='users:login')
def updateConcreteQuantity(request, pk):
    quantity = Concrete.objects.get(id=pk)    
    constructionObj = quantity.owner

    form = ConcreteForm(instance=quantity)

    if request.method == 'POST':
        form = ConcreteForm(request.POST, instance=quantity)
        if form.is_valid():
            quantity = form.save(commit=False)
            quantity.save()
            messages.success(request, 'Quantity was updated')            
            pre_url = '/concrete-positions/{id}'.format(id=quantity.owner.id)
            return redirect(pre_url)

    context = {'form':form, 'construction':constructionObj}
    return render(request, 'constructions/add_quantity.html', context)

@login_required(login_url='users:login')

def deleteConcreteQuantity(request, pk):
    quantity = Concrete.objects.get(id=pk)

    if request.method == 'POST':
        quantity.delete()
        messages.success(request, 'Quantity was deleted')
        pre_url = '/concrete-positions/{id}'.format(id=quantity.owner.id)
        return redirect(pre_url)

    context = {
        'object':quantity,
    }
    
    return render(request, 'constructions/delete_template.html', context)

# Reinforcement operations
@login_required(login_url='users:login')
def addReinforcementQuantity(request, pk):
    constructionObj = Construction.objects.get(id=pk)
    form = ReinforcementForm()

    if request.method == 'POST':
        form = ReinforcementForm(request.POST)
        if form.is_valid():
            quantity = form.save(commit=False)
            quantity.owner = constructionObj
            quantity.save()
            messages.success(request, 'Quantity was added')

constructions/templates/constructions/add_measure_unit.html
{% extends 'main.html' %}

{% block content %}
   
    <main class="formPage">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{{request.META.HTTP_REFERER}}">&#10006</a>
                <br>
    
                <form id="construction__form" action="" class="add__form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
    
                        <!-- Input:Text -->
                        <div class="form__field">
                            <label class="form__label" for="formInput#text">{{field.label}} 
                                {% if field.label == "Measure Unit" %}
                                    <a class="add__measure_unit" href="{% url 'constructions:add-measure-unit' %}">➕</a>
                                    <a class="remove__measure_unit" href="{% url 'constructions:remove-measure-unit' %}">➖</a>
                                {% endif %}
                            </label>
                            <p>{{field}}</p>
                            
                        </div>                        
                                                    
                    {% endfor %}
    
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
    
{% endblock content %}
    

constructions/templates/constructions/concrete_positions.html
{% extends 'main.html' %}

{% block content %}

<main>  
        <section class="search__add-section">

            <h3 class=singleConstruction__subtitle>Concrete Quantities for <a class="subtitle__link" href="{% url 'constructions:construction' construction.id %}">{{construction}}</a></h3>
            <div class="search__add">
                <form class="form" action="#" method="get">
                    <div class="form__field">
                        <input class="input input--text" id="formInput#search" type="text" name="search_query" value="{{search_query}}"
                        placeholder="Search for position" />
                    </div>
        
                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
                
        </section>
        <section class="data">
            <div class="data__operations">
                <button class="btn add__operation sort">Sort &darr;</button>

                {% if request.user.profile == construction.owner %}
                    <a class="add__operation" id="add_new" href="{% url 'constructions:add-concrete-quantity' construction.id %}">➕ New Quantity</a>
                {% endif %}

                <div class="data__total">
                    <label for="quantity">Total:</label>
                        <p id="total"></p>
                        <p id="measure__unit"></p>
                </div>                
            </div>           
            
            <div class="data__container">
                {% for quantity in quantities %}
                    {% if quantity.owner == construction %}        
                    
                        <div class="data__features">
                            <div class="data__feature">
                                <label for="created">Created:</label>
                                <p>{{quantity.created|date:"d M, Y"}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="created">Date:</label>
                                <p>{{quantity.date|date:"d M, Y"}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="name">Name:</label>
                                <p>{{quantity.name}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="custom_name">Custom Name:</label>
                                <p>{{quantity.custom_name}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="quantity">Quantity:</label>
                                <p class="data__quantity">{{quantity.quantity}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="measure_unit">Unit:</label>
                                <p class="measure__units">{{quantity.measure_unit_dropdown}}</p>
                            </div>

                            {% if request.user.profile == construction.owner %}
                                <div class="data__operations">
                                    <a class="operation" href="{% url 'constructions:update-concrete-quantity' quantity.id %}">Edit</a>
                                    <a class="operation" id="delete" href="{% url 'constructions:delete-concrete-quantity' quantity.id %}">Delete</a>
                                </div>
                            {% endif %} 

                        </div>
                    {% endif %}    
                {% endfor %}
            </div>
        </section>
</main>

{% endblock content %}

constructions/templates/constructions/construction_form.html
{% extends 'main.html' %}

{% block content %}       

<main class="formPage">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'users:account' %}">&#10006</a>
            <br>

            <form id="construction__form" action="" class="add__form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label class="form__label" for="formInput#text">{{field.label}}</label>
                        <p>{{field}}</p>
                    </div>
                    
                {% endfor %}                

                <div class="form__field">
                    <label class="form__label" for="formInput#text">Tags</label>
                    <textarea name="newtags" class="input" placeholder="Add main positions" maxlength="25"></textarea>
                </div>

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}
    

constructions/templates/constructions/earth_positions.html
{% extends 'main.html' %}

{% block content %}

<main>  
        <section class="search__add-section">

            <h3 class=singleConstruction__subtitle>Earth Quantities for <a class="subtitle__link" href="{% url 'constructions:construction' construction.id %}">{{construction}}</a></h3>
            <div class="search__add">
                <form class="form" action="#" method="get">
                    <div class="form__field">
                        <input class="input input--text" id="formInput#search" type="text" name="search_query" value="{{search_query}}"
                        placeholder="Search for position" />
                    </div>
        
                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
                
        </section>
        <section class="data">
            <div class="data__operations">
                <button class="btn add__operation sort">Sort &darr;</button>
                
                {% if request.user.profile == construction.owner %}
                    <a class="add__operation" id="add_new" href="{% url 'constructions:add-earth-quantity' construction.id %}">➕ New Quantity</a>
                {% endif %}

                <div class="data__total">
                    <label for="quantity">Total:</label>
                        <p id="total"></p>
                        <p id="measure__unit"></p>
                </div>                
            </div>           
            
            <div class="data__container">
                {% for quantity in quantities %}        
                    {% if quantity.owner == construction %}
                    
                        <div class="data__features">
                            <div class="data__feature">
                                <label for="created">Created:</label>
                                <p>{{quantity.created|date:"d M, Y"}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="created">Date:</label>
                                <p>{{quantity.date|date:"d M, Y"}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="name">Name:</label>
                                <p>{{quantity.name}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="custom_name">Custom Name:</label>
                                <p>{{quantity.custom_name}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="quantity">Quantity:</label>
                                <p class="data__quantity">{{quantity.quantity}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="measure_unit">Unit:</label>
                                <p class="measure__units">{{quantity.measure_unit_dropdown}}</p>
                            </div>

                            {% if request.user.profile == construction.owner %}
                                <div class="data__operations">
                                    <a class="operation" href="{% url 'constructions:update-earth-quantity' quantity.id %}">Edit</a>
                                    <a class="operation" id="delete" href="{% url 'constructions:delete-earth-quantity' quantity.id %}">Delete</a>
                                </div>
                            {% endif %} 
                            
                        </div>
                        
                        {% endif %}
                        
                {% endfor %}
                
            </div>            
        </section>        
</main>

{% endblock content %}

constructions/templates/constructions/others_positions.html
{% extends 'main.html' %}

{% block content %}

<main>  
        <section class="search__add-section">

            <h3 class=singleConstruction__subtitle>Other Quantities for <a class="subtitle__link" href="{% url 'constructions:construction' construction.id %}">{{construction}}</a></h3>
            <div class="search__add">
                <form class="form" action="#" method="get">
                    <div class="form__field">
                        <input class="input input--text" id="formInput#search" type="text" name="search_query" value="{{search_query}}"
                        placeholder="Search for position" />
                    </div>
        
                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
                
        </section>
        <section class="data">
            <div class="data__operations">
                <button class="btn add__operation sort">Sort &darr;</button>

                {% if request.user.profile == construction.owner %}
                    <a class="add__operation" id="add_new" href="{% url 'constructions:add-others-quantity' construction.id %}">➕ New Quantity</a>
                {% endif %}

                <div class="data__total">
                    <label for="quantity">Total:</label>
                        <p id="total"></p>
                        <p id="measure__unit"></p>
                </div>                
            </div>           
            
            <div class="data__container">
                {% for quantity in quantities %}        
                    {% if quantity.owner == construction %} 
                        <div class="data__features">
                            <div class="data__feature">
                                <label for="created">Created:</label>
                                <p>{{quantity.created|date:"d M, Y"}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="created">Date:</label>
                                <p>{{quantity.created|date:"d M, Y"}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="name">Name:</label>
                                <p>{{quantity.name}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="custom_name">Custom Name:</label>
                                <p>{{quantity.custom_name}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="quantity">Quantity:</label>
                                <p class="data__quantity">{{quantity.quantity}}</p>
                            </div>
                            <div class="data__feature">
                                <label for="measure_unit">Unit:</label>
                                <p class="measure__units">{{quantity.measure_unit_dropdown}}</p>
                            </div>

                            {% if request.user.profile == construction.owner %}
                                <div class="data__operations">
                                    <a class="operation" href="{% url 'constructions:update-others-quantity' quantity.id %}">Edit</a>
                                    <a class="operation" id="delete" href="{% url 'constructions:delete-others-quantity' quantity.id %}">Delete</a>
                                </div>
                            {% endif %} 

                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </section>
</main>

{% endblock content %}
    

constructions/templates/constructions/single-construction.html
{% extends 'main.html' %}


{% block content %}  

<main>
    <section class="info">
        <div class="image__container">
            <img src="{{construction.imageURL_single_construction}}" alt="Construction Image">
        </div>
        
        <div class="construction-bio">
            <h2 class="singleConstruction__title">{{construction.title}}</h2>
            <h3 class="singleConstruction__subtitle">About the Construction</h3>
            <div class="singleConstruction__info">{{construction.description}}</div>            
            <h3 class="singleConstruction__subtitle">Main Positions</h3>
            <div class="singleConstruction__positionStack">
                {% for tag in construction.tags.all|slice:'8' %}
                    <span class="tag__lg">
                        <small>{{tag}}</small>
                    </span>
                {% endfor %}
            </div>
        </div>
    </section>  

    <section class="main__positions">
        <div class="main__positions-links">
            <a class="main__position-link" href="{% url 'constructions:earth-positions' construction.id %}"><h2>Earth</h2></a>
            <a class="main__position-link" href="{% url 'constructions:concrete-positions' construction.id %}"><h2>Concrete</h2></a>
            <a class="main__position-link" href="{% url 'constructions:reinforcement-positions' construction.id %}"><h2>Reinforcement</h2></a>
            <a class="main__position-link" href="{% url 'constructions:others-positions' construction.id %}"><h2>Others</h2></a>
            <a class="main__position-link" href="{% url 'constructions:summary-positions' construction.id %}"><h2>Summary</h2></a>
        </div>
    </section>
   
</main>

{% endblock content %}