api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('constructions/', views.getConstructions),
    path('constructions/<str:pk>/', views.getConstruction),
    path('constructions/<str:pk>/addearth/', views.addEarth),
    path('constructions/<str:pk>/addconcrete/', views.addConcrete),
    path('constructions/<str:pk>/addreinforcement/', views.addReinforcement),
    path('constructions/<str:pk>/addothers/', views.addOthers),

    path('remove-tag/', views.removeTag),
]

constructions/urls.py
from django.urls import path
from . import views

app_name = 'constructions'

urlpatterns = [
    path('', views.constructions, name='constructions'),
    path('construction/<str:pk>', views.construction, name='construction'),
    path('create-construction/', views.createConstruction, name='create-construction'),
    path('update-construction/<str:pk>', views.updateConstruction, name='update-construction'),
    path('delete-construction/<str:pk>', views.deleteConstruction, name='delete-construction'),

    path('earth-positions/<str:pk>', views.earthPositions, name='earth-positions'),
    path('concrete-positions/<str:pk>', views.concretePositions, name='concrete-positions'),
    path('reinforcement-positions/<str:pk>', views.reinforcementPositions, name='reinforcement-positions'),
    path('others-positions/<str:pk>', views.othersPositions, name='others-positions'),
    path('summary-positions/<str:pk>', views.summaryPositions, name='summary-positions'),

    path('add-earth-quantity/<str:pk>', views.addEarthQuantity, name='add-earth-quantity'),
    path('update-earth-quantity/<str:pk>', views.updateEarthQuantity, name='update-earth-quantity'),
    path('delete-earth-quantity/<str:pk>', views.deleteEarthQuantity, name='delete-earth-quantity'),

    path('add-concrete-quantity/<str:pk>', views.addConcreteQuantity, name='add-concrete-quantity'),
    path('update-concrete-quantity/<str:pk>', views.updateConcreteQuantity, name='update-concrete-quantity'),
    path('delete-concrete-quantity/<str:pk>', views.deleteConcreteQuantity, name='delete-concrete-quantity'),

    path('add-reinforcement-quantity/<str:pk>', views.addReinforcementQuantity, name='add-reinforcement-quantity'),
    path('update-reinforcement-quantity/<str:pk>', views.updateReinforcementQuantity, name='update-reinforcement-quantity'),
    path('delete-reinforcement-quantity/<str:pk>', views.deleteReinforcementQuantity, name='delete-reinforcement-quantity'),

    path('add-others-quantity/<str:pk>', views.addOthersQuantity, name='add-others-quantity'),
    path('update-others-quantity/<str:pk>', views.updateOthersQuantity, name='update-others-quantity'),
    path('delete-others-quantity/<str:pk>', views.deleteOthersQuantity, name='delete-others-quantity'),

    path('add-measure-unit/', views.addMeasureUnit, name='add-measure-unit'),
    path('remove-measure-unit/', views.removeMeasureUnit, name='remove-measure-unit'),

    path('export-excel/<str:pk>', views.exportExcel, name='export-excel'),
]

quantitycheck/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [   

    path('admin/', admin.site.urls),
    path('', include('constructions.urls')),    
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='reset_password_sent.html'), name='password_reset_done'),   
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='reset.html'), name='password_reset_confirm'),   
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'), name='password_reset_complete'),   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),

    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userProfile, name='user-profile'),

    path('account/', views.userAccount, name='account'),
    path('edit-account/', views.editAccount, name='edit-account'),
    path('delete-account/<str:pk>', views.deleteAccount, name='delete-account'),

    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.viewMessage, name='message'),
    path('create-message/<str:pk>/', views.createMessage, name='create-message'),
    path('delete-message/<str:pk>/', views.deleteMessage, name='delete-message'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    username = models.CharField(max_length=50, blank=True, null=True)
    location = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    short_intro = models.CharField(max_length=150, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='profiles/user-default.png')
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.user.username)

    class Meta:
        ordering = ['-created']

    @property
    def imageURL_profile(self):
        try:
            url = self.profile_image.url
        except:
            url = '/static/images/profiles/user-default.png'

        return url

class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='messages')
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.subject)

    class Meta:
        ordering = ['is_read', 'created']

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . models import Profile, Message
from constructions.models import Tag

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name':'Name',
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'username', 'location', 'short_intro', 'bio', 'profile_image']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})
        
            self.fields['bio'].widget.attrs.update({'class':''})
            self.fields['profile_image'].widget.attrs.update({'class':''})


class PositionForm(ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'
        exclude = ['owner', 'id']

    def __init__(self, *args, **kwargs):
        super(PositionForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

            self.fields['body'].widget.attrs.update({'class':''})

users/views.py
from django.shortcuts import render, redirect
from . models import Profile, Message
from django.contrib.auth.models import User
from constructions.models import Construction, Tag
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from . forms import CustomUserCreationForm, ProfileForm, PositionForm, MessageForm
from django.contrib.auth.decorators import login_required
from . utils import searchProfiles, paginateProfiles

# Create your views here.
def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('constructions:constructions')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('constructions:constructions')
        else:
            messages.error(request, 'Username OR Password is incorrect')

    return render(request, 'users/login_register.html')

def logoutUser(request):
    logout(request)
    messages.info(request, 'User was logged out')
    return redirect('users:login')

def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, 'User account was created')

            login(request, user)
            return redirect('users:edit-account')

        else:
            messages.error(request, 'An error has occured during registration')



    context = {'page':page, 'form':form}
    return render(request, 'users/login_register.html', context)

def profiles(request):
    profiles, search_query = searchProfiles(request)
    custom_range, profiles = paginateProfiles(request, profiles, 6)
    context = {'profiles': profiles, 'search_query': search_query, 'custom_range': custom_range}

    return render(request, 'users/profiles.html', context)

def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)    
    constructions = Construction.objects.all()
    context = {'profile':profile, 'constructions':constructions}
    return render(request, 'users/user-profile.html', context)

@login_required(login_url='login')
def userAccount(request):
    profile = request.user.profile
    constructions = profile.construction_set.all()

    context = {'profile':profile, 'constructions':constructions}
    return render(request, 'users/account.html', context)

@login_required(login_url='login')
def editAccount(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('users:account')

    context = {'form':form}
    return render(request, 'users/profile_form.html', context)

def deleteAccount(request, pk):
    profile = request.user.profile
    if request.method == 'POST':
        profile.delete()
        messages.success(request, 'Your profile was deleted succesfully')
        return redirect('constructions:constructions')
    context = {'object':profile}
    return render(request, 'users/delete_template.html', context)

@login_required(login_url='login')
def inbox(request):
    profile = request.user.profile
    messageRequests = profile.messages.all()
    numberOfMessages = messageRequests.count()
    unreadCount = messageRequests.filter(is_read=False).count()
    context = {
        'messageRequests':messageRequests,
        'numberOfMessages':numberOfMessages,
        'unreadCount':unreadCount,
    }
    return render(request, 'users/inbox.html', context)

@login_required(login_url='login')
def viewMessage(request, pk):
    profile = request.user.profile
    message = profile.messages.get(id=pk)
    if message.is_read == False:
        message.is_read = True
        message.save()
    context = {'message':message}
    return render(request, 'users/message.html', context)

def createMessage(request, pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()

    try:
        sender = request.user.profile
    except:
        sender = None

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.name
                message.email = sender.email
            message.save()

            messages.success(request, 'Your message was successfully sent')
            return redirect('users:user-profile', pk=recipient.id)

    context = {'recipient':recipient, 'form':form}
    return render(request, 'users/message_form.html', context)

def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)
    if request.method == 'POST':
        message.delete()
        messages.success(request, 'The message was deleted')
        return redirect('users:inbox')
    context = {'object':message}
    return render(request, 'users/delete_template.html', context)

users/templates/users/account.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<main>
    <div class="profile__container">
        <div class="layout">
            <div class="profile__card">
                <img class="profile__photo" src="{{profile.imageURL_profile}}" alt="Profile Image">
                <h2 class="engineer__name">{{profile.name}}</h2>
                <p class="engineer__title">{{profile.short_intro}}</p>
                <p class="engineer__location">Location: {{profile.location}}</p>
                <p class="engineer__email">Contact: {{profile.email}}</p>
                <a href="{% url 'users:edit-account' %}" class="btn btn--sub btn--lg">Edit Account</a>
                <a href="{% url 'users:delete-account' profile.id %}" class="btn btn--sub btn--lg">Delete Account</a>
            </div>
            <div class="profile__info">
                <h2>About Me</h2>
                <p>{{profile.bio|slice:'1000'}}</p>

                <div class="my__constructions">
                    <h2>My Constructions</h2>
                    <a class="add__operation" href="{% url 'constructions:create-construction' %}">➕ New Construction</a>
                </div>
                
                
                <div class="construction__tags-account">
                    {% for construction in constructions %}

                        {% if construction.owner.name == profile.name %}                             

                            <div class="construction__features">
                                
                                <div class="feature">
                                    <label for="image">Image</label>
                                    <a href="{% url 'constructions:construction' construction.id %}"><img class="construction__thumbnail" src="{{construction.imageURL_single_construction}}" alt="Project Thumbnail" /></a>
                                </div>

                                <div class="feature">
                                    <label for="name">Name</label>
                                    <a href="{% url 'constructions:construction' construction.id %}" class="construction__tag"><span >{{construction}}</span></a>
                                </div>

                                <div class="feature">
                                    <label for="description">Description</label>
                                    <p>{{construction.description|slice:'150'}}</p>
                                </div>
                                
                                <div class="feature_positions">
                                    <label for="description" class="positions">Positions: </label>
                                        <div class="feature_positions-grid">
                                            {% for tag in construction.tags.all|slice:'6' %}
                                                    <span class="tag__lg position__hide">
                                                        <small>{{tag}}</small><small data-tag="{{tag.id}}" data-construction="{{construction.id}}" class="deletePosition">&#10006</small>
                                                    </span>
                                            {% endfor %}
                                        </div>
                                </div>                                 

                                <div class="operations">
                                    <a class="operation" href="{% url 'constructions:update-construction' construction.id %}">Edit</a>
                                    <a class="operation" href="{% url 'constructions:delete-construction' construction.id %}?next=/users/account/">Delete</a>
                                </div>  
                            </div>
                        {% endif %}
                                
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}
    

users/templates/users/delete_template.html
{% extends 'main.html' %}


{% block content %}
    <form action="" class="delete__form" method="POST">
        {% csrf_token %}
        <p class="delete__message">Are you sure you want to delete "{{object}}"?</p>
        <a class="add__operation" href="{{request.META.HTTP_REFERER}}">Go Back</a>
        <input class="add__operation" type="submit" value="Confirm">
    </form>
{% endblock content %}
    

users/templates/users/hide_position.html
{% extends 'main.html' %}


{% block content %}
    <form action="" class="delete__form" method="POST">
        {% csrf_token %}
        <p class="delete__message">Are you sure you want to hide "{{object}}"?</p>
        <a class="add__operation" href="{{request.GET.next}}">Go Back</a>
        <input class="add__operation" type="submit" value="Confirm">
    </form>
{% endblock content %}
    

users/templates/users/inbox.html
{% extends 'main.html' %}


{% block content %}
  <!-- Main Section -->
<main>
  <div class="content-box">
    <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
    {% if numberOfMessages == 0 %}
    <ul class="messages">
      <p class="message__empty">Your inbox is empty.</p>
    </ul>
    {% else %}
      <ul class="messages">
          
        {% for message in messageRequests %}
          
          {% if message.is_read == False %}
            <li class="message message--unread">
          {% else %}
            <li class="message">
          {% endif %}
            
            <a href="{% url 'users:message' message.id %}">
              <span class="message__author">{{message.name}}</span>
              <span class="message__subject">{{message.subject}}</span>
              <span class="message__date">{{message.created}}</span>
            </a>
          </li>           
        {% endfor %}        
        
      </ul>
    {% endif %}
  </div>
</main> 

{% endblock content %}
  

users/templates/users/login_register.html
{% extends 'main.html' %}
{% load static %}
{% block content %}


{% if page == 'register' %}

    <div class="auth">
        <div class="card">
          <div class="auth__header text-center">
            <img class="logo__image" src="{% static 'images/logo.svg' %}" alt="icon" />        
            <h3>Register an Account</h3>
            <p>Create a new engineer account</p>
          </div>
  
          <form action="{% url 'users:register' %}" method="POST" class="form auth__form">
            {% csrf_token %}

            
            {% for field in form %}
                
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}: </label>
                    {{field}}

                    
                    <!-- {% if field.help_text %}
                        <small>{{field.help_text}}</small>
                    {% endif %} -->

                    
                    {% for error in field.errors %}
                        <p class="form__fields-messages">{{error}}</p>
                    {% endfor %}                       
                        
                </div> 

            {% endfor %}           
          
            <div class="auth__actions">
              <input class="btn btn--sub btn--lg" type="submit" value="Sign In" />
            </div>
          </form>
          <div class="auth__alternative">
            <p>Already have an Account?</p>
            <a href="{% url 'users:login' %}">Log In</a>
          </div>
        </div>
    </div>

{% else %} 

    <div class="auth">
        <div class="card">
            <div class="auth__header text-center">                
                <img class="logo__image" src="{% static 'images/logo.svg' %}" alt="icon" />                
                <h3>Account Login</h3>
                <p>Hello Enginner, Welcome Back!</p>
            </div>

            <form action="{% url 'users:login' %}" method="POST" class="form auth__form">
                {% csrf_token %}

                <!-- Input:Username -->
                <div class="form__field">
                <label for="formInput#text">Username: </label>
                <input
                    class="input input--text"
                    id="formInput#text"
                    type="text"
                    name="username"
                    placeholder="Enter your username..."
                />
                </div>

                <!-- Input:Password -->
                <div class="form__field">
                <label for="formInput#password">Password: </label>
                <input
                    class="input input--password"
                    id="formInput#passowrd"
                    type="password"
                    name="password"
                    placeholder="••••••••"
                />
                </div>
                <div class="auth__actions">
                <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
                <a href="{% url 'reset_password' %}">Forget Password?</a>
                </div>
            </form>
            <div class="auth__alternative">
                <p>Don’t have an Account?</p>
                <a href="{% url 'users:register' %}">Sign Up</a>
            </div>
        </div>
    </div>

{% endif %}

{% endblock content %}
    

users/templates/users/message.html
{% extends 'main.html' %}


{% block content %}
  <!-- Main Section -->
  <main>
    <div class="content-box">
      <div class="message__container">
        <a class="backButton" href="{% url 'users:inbox' %}">&#10006</a>
        <h2 class="message__subject-lg">{{message.subject}}</h4>

          
          {% if message.sender.user %}
          <a href="{% url 'users:user-profile' message.sender.id %}" class="message__author-lg">{{message.name}}</a>
          {% else %}
          <a href="" class="message__author-lg">{{message.name}}</a>
          {% endif %}
            
          <p class="message__date-lg">{{message.created}}</p>
          <div class="message__body-lg">{{message.body|linebreaksbr}}</div>
          <a class="operation message__delete" href="{% url 'users:delete-message' message.id %}">Delete</a>
      </div>
    </div>
  </main>
{% endblock content %}
  

users/templates/users/message_form.html
{% extends 'main.html' %}


{% block content %}
    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'users:user-profile' recipient.id %}">&#10006</a>
                <br>

                <form class="add__form" method="POST">
                    {% csrf_token %}
                    
                    {% if request.user.is_authenticated == False %}   

                        <div class="form__field">
                            <label for="formInput#text"> {{form.name.label}}</label>
                            {{form.name}}
                        </div>
                        <div class="form__field">
                            <label for="formInput#text"> {{form.email.label}}</label>
                            {{form.email}}
                        </div>

                    {% endif %}                        
                            
                    <div class="form__field">
                        <label for="formInput#text"> {{form.subject.label}}</label>
                        {{form.subject}}
                    </div>
                    <div class="form__field">
                        <label for="formInput#text"> {{form.body.label}}</label>
                        {{form.body}}
                    </div>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock content %}
    
 

users/templates/users/position_form.html
{% extends 'main.html' %}

{% block content %}
<main class="formPage">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'users:account' %}">&#10006</a>
            <br>

            <form action="" class="add__form" method="POST">
                {% csrf_token %}
                {% for field in form %}

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label class="form__label" for="formInput#text">{{field.label}}</label>
                        <p>{{field}}</p>
                    </div>
                    
                {% endfor %}

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>
{% endblock content %}
    

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

<main class="profiles__page">
    <section class="hero__section">
        <div class="hero__section-container">
            <div class="search__section__text">
                <h2>CONTACT AN <span>ENGINEER</span></h2>
                <h2>FOR ANY REQUEST</h2>
            </div>

            <div class="hero-section__search">
                <form id="searchForm" class="form" action="{% url 'users:profiles' %}" method="get">
                <div class="form__field">
                    <input class="input input--text" id="formInput#search" type="text" name="search_query"
                    placeholder="Search by engineer name" value="{{search_query}}" />
                </div>
    
                <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>

     <section class="profiles__list">
        <div class="container">
            <div class="grid grid--three">
                {% for profile in profiles %}
                <a href="{% url 'users:user-profile' profile.id %}" class="card__body">
                    <div class="profiles__card">
                            <div class="profiles__profile">
                                <img class="profiles__photo" src="{{profile.imageURL_profile}}" alt="image" />
                                <div class="profiles__meta">
                                    <h3>{{profile.name}}</h3>
                                    <h5>{{profile.short_intro|slice:"60"}}</h5>
                                </div>
                                <p class="engineer_info">{{profile.bio|truncatewords:50}}</p>
                                <p class="engineer_email"><span>Contact:</span> {{profile.email}}</p>
                            </div>                            
                    </div> 
                </a>
                {% endfor %}
            </div>
        </div>               
      </section>

      {% include 'pagination.html' with queryset=profiles custom_range=custom_range %}

    </main>

{% endblock content %}
    

    

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}

<main class="profile">
    <div class="profile__container">
        <div class="layout">
            <div class="profile__card">
                <img class="profile__photo" src="{{profile.profile_image.url}}" alt="Profile Image">
                <h2 class="engineer__name">{{profile.name}}</h2>
                <p class="engineer__title">{{profile.short_intro}}</p>
                <p class="engineer__location">Location: {{profile.location}}</p>
                <p class="engineer__email">Contact: {{profile.email}}</p>
                
                {% if request.user.profile.id != profile.id %}

                    <a href="{% url 'users:create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
                    
                {% endif %}
                    
            </div>
            <div class="profile__info">
                <h2>About Me</h2>
                <p>{{profile.bio|slice:'1000'}}</p>
                <h2>My Constructions</h2>
                
                
                <div class="construction__tags">
                    {% for construction in constructions %}

                        {% if construction.owner.name == profile.name %}
                            <a href="{% url 'constructions:construction' construction.id %}" class="construction__tag"><span >{{construction}}</span></a>
                        {% endif %}
                                
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

    