api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('constructions/', views.getConstructions),
    path('constructions/<str:pk>/', views.getConstruction),
    path('constructions/<str:pk>/addearth/', views.addEarth),
    path('constructions/<str:pk>/addconcrete/', views.addConcrete),
    path('constructions/<str:pk>/addreinforcement/', views.addReinforcement),
    path('constructions/<str:pk>/addothers/', views.addOthers),

    path('remove-tag/', views.removeTag),
]

constructions/urls.py
from django.urls import path
from . import views

app_name = 'constructions'

urlpatterns = [
    path('', views.constructions, name='constructions'),
    path('construction/<str:pk>', views.construction, name='construction'),
    path('create-construction/', views.createConstruction, name='create-construction'),
    path('update-construction/<str:pk>', views.updateConstruction, name='update-construction'),
    path('delete-construction/<str:pk>', views.deleteConstruction, name='delete-construction'),

    path('earth-positions/<str:pk>', views.earthPositions, name='earth-positions'),
    path('concrete-positions/<str:pk>', views.concretePositions, name='concrete-positions'),
    path('reinforcement-positions/<str:pk>', views.reinforcementPositions, name='reinforcement-positions'),
    path('others-positions/<str:pk>', views.othersPositions, name='others-positions'),
    path('summary-positions/<str:pk>', views.summaryPositions, name='summary-positions'),

    path('add-earth-quantity/<str:pk>', views.addEarthQuantity, name='add-earth-quantity'),
    path('update-earth-quantity/<str:pk>', views.updateEarthQuantity, name='update-earth-quantity'),
    path('delete-earth-quantity/<str:pk>', views.deleteEarthQuantity, name='delete-earth-quantity'),

    path('add-concrete-quantity/<str:pk>', views.addConcreteQuantity, name='add-concrete-quantity'),
    path('update-concrete-quantity/<str:pk>', views.updateConcreteQuantity, name='update-concrete-quantity'),
    path('delete-concrete-quantity/<str:pk>', views.deleteConcreteQuantity, name='delete-concrete-quantity'),

    path('add-reinforcement-quantity/<str:pk>', views.addReinforcementQuantity, name='add-reinforcement-quantity'),
    path('update-reinforcement-quantity/<str:pk>', views.updateReinforcementQuantity, name='update-reinforcement-quantity'),
    path('delete-reinforcement-quantity/<str:pk>', views.deleteReinforcementQuantity, name='delete-reinforcement-quantity'),

    path('add-others-quantity/<str:pk>', views.addOthersQuantity, name='add-others-quantity'),
    path('update-others-quantity/<str:pk>', views.updateOthersQuantity, name='update-others-quantity'),
    path('delete-others-quantity/<str:pk>', views.deleteOthersQuantity, name='delete-others-quantity'),

    path('add-measure-unit/', views.addMeasureUnit, name='add-measure-unit'),
    path('remove-measure-unit/', views.removeMeasureUnit, name='remove-measure-unit'),

    path('export-excel/<str:pk>', views.exportExcel, name='export-excel'),
]

quantitycheck/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [   

    path('admin/', admin.site.urls),
    path('', include('constructions.urls')),    
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='reset_password_sent.html'), name='password_reset_done'),   
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='reset.html'), name='password_reset_confirm'),   
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'), name='password_reset_complete'),   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),

    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userProfile, name='user-profile'),

    path('account/', views.userAccount, name='account'),
    path('edit-account/', views.editAccount, name='edit-account'),
    path('delete-account/<str:pk>', views.deleteAccount, name='delete-account'),

    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.viewMessage, name='message'),
    path('create-message/<str:pk>/', views.createMessage, name='create-message'),
    path('delete-message/<str:pk>/', views.deleteMessage, name='delete-message'),
]

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'styles/constructions.css' %}" media="screen" type="text/css">
        <link rel="stylesheet" href="{% static 'styles/single-construction.css' %}" media="screen" type="text/css">
        <link rel="stylesheet" href="{% static 'styles/form.css' %}" media="screen" type="text/css">
        <link rel="stylesheet" href="{% static 'styles/profiles.css' %}" media="screen" type="text/css">
        <link rel="stylesheet" href="{% static 'styles/single-profile.css' %}" media="screen" type="text/css">
        <link rel="stylesheet" href="{% static 'styles/alerts.css' %}" media="screen" type="text/css">
        <link rel="stylesheet" href="{% static 'styles/account.css' %}" media="screen" type="text/css">
        <link rel="stylesheet" href="{% static 'styles/data.css' %}" media="screen" type="text/css">
        <link rel="stylesheet" href="{% static 'styles/inbox.css' %}" media="screen" type="text/css">
        <link rel="stylesheet" href="{% static 'styles/responsive.css' %}" media="screen" type="text/css">

        <script defer src="{% static 'js/app.js' %}"></script>
        <script defer src="{% static 'js/pagination.js' %}"></script>
        <title>QuantityCheck</title>
    </head>
    <body>
        {% include 'navbar.html' %}

        {% if messages %}            
        
            {% for message in messages  %}
                <div class="alert alert--{{message.tags}}">
                    <p class="alert__message">{{message}}</p>
                    <button class="alert__close">&#10006</button>
                </div>
            {% endfor %}            
            
        {% endif %}
            
            
        {% block content %}
            
        {% endblock content %}
    
    </body>
</html>

templates/navbar.html
{% load static %}

<!-- Header Section -->
<header>
    <div class="container__logo">
        <a class="logo" href="{% url 'constructions:constructions' %}">
            <img class="logo__image" src="{% static 'images/logo.svg' %}" alt="QuantityCheck Logo">
            <span class="logo__name">QuantityCheck</span>
        </a>
    </div>

    <nav class="header__nav">
        <ul class="header__menu">
            <div>
                <button class="menu__btn"><img class="menu__image" src="{% static 'images/menu.svg' %}" alt=""></button>
                <button class="close__menu-btn"><img class="menu__image" src="{% static 'images/close.svg' %}" alt=""></button>
            </div>
            <li class="header__menuItem close"><a href="{% url 'users:profiles' %}">Enginners</a></li>
            <li class="header__menuItem close"><a href="{% url 'constructions:constructions' %}">Constructions</a></li>
            
            
            {% if request.user.is_authenticated %}
            
            <li class="header__menuItem close"><a href="{% url 'users:account' %}">My Account</a></li>
            <li class="header__menuItem close"><a href="{% url 'users:inbox' %}">Inbox</a></li>
            <li class="header__menuItem close"><a href="{% url 'users:logout' %}">Logout</a></li>

            {% else %}
            
            <li class="header__menuItem close"><a href="{% url 'users:login' %}">Login/Sign Up</a></li>

            {% endif %}
                
        </ul>
    </nav>
    
</header>

templates/pagination.html
{% if queryset.has_other_pages %}
<div class="pagination">
  <ul class="pagination__container">

      
      {% if queryset.has_previous %}

          <li><a href="?page={{queryset.previous_page_number }}" class="pagination__btn pagination__btn-disabled" data-page="{{queryset.previous_page_number}}">&#10094; Prev</a></li>

      {% endif %}            
      
      {% for page in custom_range %}        
      
      {% if page == queryset.number %}

          <li><a href="?page={{page}}" class="pagination__btn pagination__btn-active" data-page="{{page}}">{{page}}</a></li>

      {% else %}

          <li><a href="?page={{page}}" class="pagination__btn" data-page="{{page}}">{{page}}</a></li>
      
      {% endif %}

      {% endfor %}
      
      
      {% if queryset.has_next %}
          
          <li><a href="?page={{queryset.next_page_number}}" class="pagination__btn" data-page="{{queryset.next_page_number}}">Next &#10095;</a></li>
      
      {% endif %}
          
  </ul>
</div>
{% endif %}

templates/reset.html
{% extends 'main.html' %}


{% block content %}
    <main>
        <div class="password__reset">
            <h3>Enter new password</h3>
            <p>Please enter your new password twice so we can verify you typed it in correctly.</p>
            <div class="password__form">
                <form class="form" action="" method="POST">
                    {% csrf_token %}                                        
                    
                    {% for field in form %}
                        {{field.label}}
                        {{field}}

                        {% for error in field.errors %}
                            <p class="form__fields-messages">{{error}}</p>
                        {% endfor %}    
                    {% endfor %}
                    
                                                              
                        
                    <input class="operation" type="submit" value="Submit">
                </form>
            </div>            
        </div>
    </main>    
{% endblock content %}
    

templates/reset_password.html
{% extends 'main.html' %}


{% block content %}
    <main>
        <div class="password__reset">
            <h3>Password reset</h3>
            <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
            <div class="password__form">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form}}
                    <input class="operation" type="submit" value="Submit">
                </form>
            </div>            
        </div>
    </main>    
{% endblock content %}
    

templates/reset_password_complete.html
{% extends 'main.html' %}


{% block content %}
    <main>
        <div class="password__reset">
            <h3>Password reset complete</h3>
            <p>Your password has been set. You may go ahead and log in now.</p>
            <a href="{% url 'users:login' %}">Login</a>           
        </div>
    </main>    
{% endblock content %}
    

templates/reset_password_sent.html
{% extends 'main.html' %}


{% block content %}
    <main>
        <div class="password__reset">
            <h3>Password reset sent</h3>
            <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>
            If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>           
        </div>
    </main>    
{% endblock content %}
    